---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jautolog
  namespace: jautolog
spec:
  encryptedData:
    password: AgCHL4/X7bKqXHrvjyjJHN7gZI4BUUygMpObcWSe9+Je9KLP++5o9dQHJ3Kl/9yNpEhi+/zIlvd+JknyWnSEhn7hYzIksNalid/4fIhh5BHZW6rR59+ArTOJrVawj0hNp2vGGlGZvLGj22Y8Ovakk/SCyx996y3BdZZHbCHNX6lJsEkm5oDUq2BuD8xQ8/4+vax4hn9xN680rLerXl8Aumsusf/otzJtJjeCszsDXaPJPLXkXPu8LA+o0zOeyCTmKAwiua/TFPciVMKJr/GBaJAhipxUmB4HTp2gNIyc+ijLE22/EgR9whR94jrL1s7bYf24lX7qmy3aCOPKlOIZcW6lUbgt07zB2KtF0L5WRCDOOLSdoXwQbCRcZaJhZu11Xx5GWOHz69K8cUJ+pC0Sy07T54V428Ve27Vjruuqie0zjTVIQ/lVDXGlO1WD2d1UAZJZqA4/OPtrsVu56uR+SGOWoJxtHe8wrhk6rjalDZPZFhlrkjaQNd6uE3ZP/j7hoXkEGVl5gskOdSyiwcSplZqf50NHUYmWT/IBJZtLQqo4myVSq1fvTPca/GHeB2gbNIvBhFdcQemnOhiSBXUTCx0cRZLNFFW5Z0otEPGZ4OP8vzosa7FRVRNeYQxe7deIpaVLDs+z9m5rDvBT5qWgZRbxoX8Gu5P3ZsipbpxtaBwrHyiT9R8mtUKs4EiMdYlU4gnNuRf8BLFY3/VIh4MG
    username: AgCDGKhDUMVu8QGVXpuW/16YywxJDb75PVK7MH5ihqifjUsTWJUQuPIqC79UrGehEp3rotllG1mouajuFGv5qNyBVRFWWrxXV8MQ+RbT0iLPie/e9xeM6DPm1wkdqCTKAQROc2axsRVQzJSZubPxmzkzy9j54wgUQzNEnjhw3ScQ39PY/mLllCzSddLITuegVlSuiQO5GhdX7aYmTVZbyWBZbMEKPYJl61MSWRX7Pwm1fsKRRfOmEoUbTNb4/+O5mP6D5SKSOfJJGPWERv8ojcE0/fx7/qMUYqaRDjqS1RHdRfOHe5AcClg4ChOXmWrXYTNS8Gx1xN9Fej3stkuGnW5/Qk3nhmmZ2Mw4cD2Q5ftyOpGwEpQrDqZtKkw/QoyMrciO4KjHWG7eAVIJG8DR/PrNBa2HqIc1qoCUW7l84bJTzV7IsvljcTER2T//CTWtLMBnbf7Rlw0Yf4kC/swpkONCbc99iB1GDFvH34cYbe/i4DuGDQD71KsMUobnCvdIsN685moYG8jso4BLo+tYibrZ+mrkQOIxHazwQ0IOATVJZvh2YC7J9MsIB4uxmAnw4Nd4iehvHAB9PWIdYHOEdQvSNeFFCeht0lQz8JVeEG0258ao5+49tWA/Iq8nEkWqFJEVMxQLZncpEzMyiuf79uoPh9oRpWAy7XGTc8/rd8JAYdifaQR2Jlf09KMyY77nMdtYV3h5S3bp
  template:
    metadata:
      creationTimestamp: null
      name: jautolog
      namespace: jautolog
    type: Opaque
